server:
  port: 10000

  #gateway路由断言类型：  After 、Before 、Between、Cookie、Header、Host 、Method 、Path 、Query、RemoteAddr
spring:
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: http://baidu.com
          predicates:
            - After=2019-01-20T17:42:47.789-07:00[America/Denver]   #日期格式的值  路由断言 Factory

        - id: cookie_route
          uri: http://baidu.com
          predicates:
            - Cookie=chocolate, ch.p  #Cookie 路由断言 Factory有两个参数，cookie名称和正则表达式。请求包含次cookie名称且正则表达式为真的将会被匹配。

        - id: header_route
          uri: http://baidu.com
          predicates:
            - Header=X-Request-Id, \d+  #Header 路由断言 Factory有两个参数，header名称和正则表达式。请求包含次header名称且正则表达式为真的将会被匹配。

        - id: host_route
          uri: http://baidu.com
          predicates:
            - Host=**.somehost.org,**.anotherhost.org  #Host 路由断言 Factory包括一个参数：host name列表。使用Ant路径匹配规则，.作为分隔符。

        - id: method_route
          uri: http://baidu.com
          predicates:
            - Method=GET  #Method 路由断言 Factory只包含一个参数: 需要匹配的HTTP请求方式

        - id: path_route
          uri: http://baidu.com
          predicates:
            - Path=/foo/{segment},/bar/{segment}  #Path 路由断言 Factory 有2个参数: 一个Spring PathMatcher表达式列表和可选matchOptionalTrailingSeparator标识 .
          filters:
            - Hystrix=MyHystrixCommand  #Hystrix GatewayFilter允许你向网关路由引入断路器，保护你的服务不受级联故障的影响，并允许你在下游故障时提供fallback响应。
            - name: Hystrix
              args:
                name: default
                fallbackUri: forward:/fallback
