server:
  port: 8503
spring:
  application:
    name: consul-consumer
  cloud:
    consul:
      host: localhost
      port: 8500 #默认consul服务端端口
      discovery:
        service-name: consul-consumer  #注册到consul的服务名称
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  rabbitmq:
    host: dlwtm.cn
    port: 5672
    username: guest
    password: guest
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: dlwtm.cn:9300
#      repositories:
#        enabled: true
rabbitmq:
  queue: test_queue
  topic: test_topic
