server:
  port: 10001
spring:
  application:
    name: spring-boot-kafka
  kafka:
    template:
      default-topic: test   #默认topic
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
      group-id: cgroup
    listener:
      concurrency: 3
#  boot:
#    admin:
#      client:
#        url: http://localhost:9999  #springboot服务端地址
#        instance:
#          prefer-ip: true

management:
  endpoints:
    web:
      exposure:
        include: "*" #auditevents, beans, conditions, configprops, flyway, health, heapdump, httptrace, info, jolokia, logfile, loggers, liquibase, metrics, mappings, prometheus, scheduledtasks, sessions, threaddump
  endpoint:
    health:
      show-details: always

logging:
  config: classpath:logback-spring.xml
  level:
    kafka: info

