server:
  port: 8501
spring:
  application:
    name: consul-producer
  cloud:
    consul:
      host: localhost
      port: 8500 #默认consul服务端端口
      discovery:
        service-name: consul-producer  #注册到consul的服务名称
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  rabbitmq:
    host: dlwtm.cn
    port: 5672
    username: guest
    password: guest

#自定义配置
rabbitmq:
  queue: test_queue
  topic: test_topic